language: ruby
rvm:
- '2.4'
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
before_script:
- ls -al
- ls -al config
- bundle exec rake db:create
bundler_args: "--binstubs=./bundler_stubs"

deploy:
  provider: heroku
  api_key:
    secure: enlOzoWRw6uflteb2GO1FY0is2TQiJSOjZ7vZ1L9hE0WicFfyxRFr0QbRedxboWYaBbbfbKeYWdybhGbtHfLq1xxVJbF888HYJ+vchNC6U5260uhCCR7tmOQCf8zAP1r0tRVfLJIkeE/IcqTDrO8NuxI9/nV27jJ/2VcOntymcDErZ6gfmMOXrf/DSM6gvu1hkvGzSB47wJ+paMsFckDjMNUckUEgBvOwEVmfFJgzxmNwNjJunNx9hIhs/+S2XVfD/NkyLBAR59wDFABczJ06x6qtzaw+SywUtBguQii1n0lJ3gACoeeH3uruTS/JkzFp8n8T3thfgq6Yezjj7du/Js9CnCdV+IZ7lJqkG7CQhxgx+KGTE4gluZmhDNLpm7wSLe9q1MHTJhjutU5hlXbMlEzV0nEnlqiELl3CSVytYPmvOHGenM0jea+RY9FRg9+KK4kHWP+fAnBWVtXF6uLVgH1aKxwy/EhwPT1GjeNTenzyfYz1ay2KKXckaBrLESW+74lFOnxRSB0ILp+COt75c1dtZ2eEj9nJ4MjPyClHCZ1eFT3NU4Pvg23IWbgxDycSyuDq1vMrQwM8EsOrA8blccDwSF9z+Nt49StxBgZ0U1s0ObATLZQxz73hl660ZXuptA8ZgX1KKHE7hxeVgY/AtV/lniEaNRTeJYhhRv7x2o=
  app: cwsmanager
  on:
    repo: limsammy/project_cws
